pipeline {
    agent any
    tools {
        maven 'Maven_3_9'
    }    
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                powershell '.\\jenkins\\scripts\\deliverW.ps1'
            }
        }        
        stage('Complete') {
            steps {
                echo 'Job Complete rama feature1!'
            }
        }
    }
}
